name: Repackage Dify Plugin
on:
  workflow_dispatch:
    inputs:
      author:
        description: Plugin Author
        required: true
        default: sawyer-shi
      plugin:
        description: Plugin Name
        required: true
        default: seedream-aigc
      version:
        description: Plugin Version
        required: true
        default: 0.0.3

jobs:
  repackage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Checkout code
        uses: actions/checkout@v4

      # 核心修复：Python3.12
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y curl unzip

      # 修复Windows换行符+授权脚本
      - name: Fix script permission & line break
        run: |
          sed -i 's/\r$//' plugin_repackaging.sh
          chmod +x ./plugin_repackaging.sh

      # 打包脚本内置阿里云pip源，网络加速
      - name: Run repackaging script
        run: ./plugin_repackaging.sh market ${{ github.event.inputs.author }} ${{ github.event.inputs.plugin }} ${{ github.event.inputs.version }}

      - name: Upload offline difypkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: seedream-aigc-v0.0.3-offline
          path: "*.difypkg"
